### PR TITLE
f/husky

### PR DESCRIPTION
**Pull request by glebec**
Prevent ever pushing failing lint or tests with [`husky`](https://github.com/typicode/husky).

This is pretty restrictive but beats A) finding out after code was already committed and merged, or B) telling people to go back and change their PRs.

It is possible to skip (all) git hooks with `--no-verify`, e.g. `git push --no-verify`. I decided against letting students know that but you may want to add it to the README if we keep this.

Of course, students can always opt out just by removing the `prepush` hook from `package.json`. If they do that, they may as well remove `husky`.

### CODE REVIEW

**Comment by queerviolet** [comment]
I am so confused as to how this works at all, but assuming it works, I am so into it.

Does node install a global git pre commit hook it something?

**Comment by glebec** [comment]
@queerviolet: I haven't gone in great depth into the inplementation but I use it on a number of projects reliably. To my understanding it works as follows:

* On installation of husky, it runs a setup script
* The setup script augments or replaces ALL possible git hooks for your project, by concatenating its own code into the hook files and making them executable
* When ANY hookable git action runs, the corresponding project hook executes (as is normal for git — the difference being that now all hooks for the repo are enabled)
* The custom code added to the hook simply checks package.json for a corresponding script name (e.g. prepush, precommit, whatever)
* If such a script entry is found, it runs it, and the exit code determines if the hook succeeds or aborts
* if the package is uninstalled, it cleans up after itself

Pretty reasonablr overall. I had it for my fork last senior phase and while some groups removed it (same groups that wouldn't write tests or use the linter or maintain their gitignore etc. cough cough), others said they appreciated the oversight and reassurance it provided.

**Comment by glebec** [comment]
On a related note, it could also provide a teaching opportunity to show students git hooks and how they work even without a helper like husky.

**Comment by queerviolet** [comment]
Sweet, merged.

**Pull request merged**
