### PR TITLE
Add a linter, make existing code conform to the style

### PR DESCRIPTION
**Pull request by queerviolet**
It's a pretty minimal set of style rules, but the idea is to have something that enforces *some* kind of style, and catches the most significant causes of error or eye irritation.

This PR installs eslint locally, so VSC will pick it up and use it automatically, which is a nice win. Free lint! @intersim @glebec @tmkelly28 @omriBernstein

### CODE REVIEW

**Comment by glebec** [comment]
I'm traveling today but I will probably be able to take a look this evening. Something I'd like to see is to fuse this linting config / style with the linting process / scripts from glebec/bones (see https://github.com/glebec/bones/blob/master/package.json#L18), which watches and fits into the über `dev` script (https://github.com/glebec/bones/blob/master/package.json#L23). I had intended on opening a PR for some of the changes in glebec/bones earlier but this works as a reminder. ;-)

**Comment by queerviolet** [comment]
PTAL.

That dev npm script was getting bloody ridiculous. I moved it into its own file, `dev.js`. This means you can also run `node dev` to start everything, which seems nice.

Since it's now easy to run the tests along with everything else, I did that.

I don't know why the tests are failing. :( They work for me and on my CI, and I can't see this Codeship.

**Comment by glebec** [comment]
I ended up not turning my computer on today (yay). From my phone I just checked the codeship:

```
  1) /api/auth "before all" hook: Await database sync:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I'll see if I can add you to the codeship somehow. I'm not sure why you don't already just have access, I thought it was tied to our organization so if you're using a GH account in the FS org you'd see it. Maybe not though.

**Comment by glebec** [comment]
It looks like we have to add members manually, Codeship doesn't integrate with GitHub orgs / permissions? Lame. Anyway I sent you an invite.

**Pull request merged**
